SELECT * FROM dental.table;
DROP TABLE IF EXISTS data;
CREATE TEMPORARY TABLE data
SELECT Contract_Number,Plan_ID,Organization,State,County,Enrollment,preventive,comprehensive FROM dental.table;
SELECT * FROM data;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization ='Medica';
SELECT sum(Enrollment) from data WHERE State='SD' and Organization ='Medica' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization ='Medica' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization ='Humana';
SELECT sum(Enrollment) from data WHERE State='SD' and Organization ='Humana' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization ='Humana' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'Aetna?';
SELECT Organization, Enrollment from data WHERE State='SD' and Organization REGEXP 'Aetna?';
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'Aetna?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'Aetna?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'United?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='SD' and Organization REGEXP 'United?';
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'United?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'United?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'Great?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='SD' and Organization REGEXP 'Great?';
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'Great?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SD' and Organization REGEXP 'Great?' and comprehensive=1;

SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='Humana';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='MS' and Organization ='Humana';
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='Humana' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='Humana' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='WellCare';
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='WellCare' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='WellCare' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='Cigna';
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='Cigna' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization ='Cigna' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization REGEXP 'United?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='MS' and Organization REGEXP 'United?';
SELECT sum(Enrollment) from data WHERE State='MS' and Organization REGEXP 'United?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization REGEXP 'United?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization REGEXP 'Aetna?';
SELECT sum(Enrollment) from data WHERE State='MS' and Organization REGEXP 'Aetna?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='MS' and Organization REGEXP 'Aetna?' and comprehensive=1;

SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Aetna?';
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Aetna?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Aetna?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'United?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='MS' and Organization REGEXP 'United?';
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'United?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'United?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Clover?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='NJ' and Organization REGEXP 'Clover?';
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Clover?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Clover?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Blue?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='NJ' and Organization REGEXP 'Blue?';
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Blue?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Blue?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Ameri?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='NJ' and Organization REGEXP 'Ameri?';
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Ameri?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='NJ' and Organization REGEXP 'Ameri?' and comprehensive=1;

SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'United?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='SC' and Organization REGEXP 'United?';
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'United?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'United?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization ='Humana';
SELECT sum(Enrollment) from data WHERE State='SC' and Organization ='Humana' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization ='Humana' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'Aetna?';
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'Aetna?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'Aetna?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'Wellcare?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='SC' and Organization REGEXP 'Wellcare?';
SELECT sum(Enrollment) from data WHERE State='SC' and Organization ='WellCare' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization ='WellCare' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'Blue?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='SC' and Organization REGEXP 'Blue?';
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'Blue?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='SC' and Organization REGEXP 'Blue?' and comprehensive=1;

SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'United?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='SC' and Organization REGEXP 'United?';
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'United?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'United?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Aetna?';
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Aetna?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Aetna?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Connecticare?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='CT' and Organization REGEXP 'Connect?';
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Connecticare?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Connecticare?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Blue?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='CT' and Organization REGEXP 'Blue?';
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Blue?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Blue?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization REGEXP 'Wellcare?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='CT' and Organization REGEXP 'Wellcare?';
SELECT sum(Enrollment) from data WHERE State='CT' and Organization ='WellCare' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='CT' and Organization ='WellCare' and comprehensive=1;

SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'United?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='IN' and Organization REGEXP 'United?';
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'United?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'United?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization ='Humana';
SELECT sum(Enrollment) from data WHERE State='IN' and Organization ='Humana' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization ='Humana' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Blue?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='IN' and Organization REGEXP 'Blue?';
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Blue?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Blue?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Aetna?';
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Aetna?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Aetna?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Anthem Health?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='IN' and Organization REGEXP 'Anthem Health?';
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Anthem Health?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='IN' and Organization REGEXP 'Anthem Health?' and comprehensive=1;

SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'HMSA?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='HI' and Organization REGEXP 'HMSA?';
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'HMSA?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'HMSA?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'Kaiser?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='HI' and Organization REGEXP 'Kaiser?';
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'Kaiser?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'Kaiser' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'United?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='HI' and Organization REGEXP 'United?';
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'United?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'United?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization = 'Humana';
SELECT sum(Enrollment) from data WHERE State='HI' and Organization ='Humana' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization ='Humana' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization REGEXP 'Wellcare?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='HI' and Organization REGEXP 'Wellcare?';
SELECT sum(Enrollment) from data WHERE State='HI' and Organization ='WellCare' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='HI' and Organization ='WellCare' and comprehensive=1;

SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Aetna?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='PA' and Organization REGEXP 'Aetna?';
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Aetna?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Aetna?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Highmark?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='PA' and Organization REGEXP 'Highmark?';
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Highmark?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Highmark?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'UPMC?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='PA' and Organization REGEXP 'UPMC?';
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'UPMC?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'UPMC?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Geisinger?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='PA' and Organization REGEXP 'Geisinger?';
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Geisinger?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Geisinger?' and comprehensive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Keystone?';
SELECT Organization, Enrollment, preventive, comprehensive from data WHERE State='PA' and Organization REGEXP 'Keystone?';
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Keystone?' and preventive=1;
SELECT sum(Enrollment) from data WHERE State='PA' and Organization REGEXP 'Keystone?' and comprehensive=1;